import { Check, Circle, Clock, Code2, PlaySquare, Loader2 } from 'lucide-react';
import { useState } from 'react';
import axios from 'axios';
import api from '../api';

export default function RoadmapDisplay({ roadmapData, setRoadmapData }) {
  const [activeVideoModule, setActiveVideoModule] = useState(null);
  const [videos, setVideos] = useState([]);
  const [isVideoLoading, setIsVideoLoading] = useState(false);

  if (!roadmapData || !roadmapData.modules) return null;

 

// 2. Phir axios call mein usko use karo
const handleStatusUpdate = async (moduleId, currentStatus) => {
  const newStatus = currentStatus === 'completed' ? 'pending' : 'completed';
  
  try {
   const response = await api.put('/api/roadmap/update-module', { roadmapId: roadmapData._id, moduleId, newStatus });
    
    if (response.data.success) {
      setRoadmapData(response.data.roadmap);
    }
  } catch (error) {
    console.error("Error updating progress:", error);
  }
};

  const handleFetchVideos = async (topic, moduleId) => {
    if (activeVideoModule === moduleId) return setActiveVideoModule(null);
    setActiveVideoModule(moduleId);
    setIsVideoLoading(true);
    try {
const response = await api.post('/api/resources/youtube', { topic });
      if (response.data.success) setVideos(response.data.videos);
    } catch (error) {
      console.error("Error:", error);
    } finally {
      setIsVideoLoading(false);
    }
  };

  const completed = roadmapData.modules.filter(m => m.status === 'completed').length;
  const progress = Math.round((completed / roadmapData.modules.length) * 100);

  return (
    <div className="max-w-4xl mx-auto mt-12 mb-24 px-6">
      
      {/* Header */}
      <div className="mb-16 border-b border-[#EAE7DC] pb-8">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div>
            <h2 className="font-serif text-4xl text-[#1A1A1A] mb-2">{roadmapData.title || roadmapData.goal}</h2>
            <p className="text-[#666666] font-light">Structured curriculum generated by AI.</p>
          </div>
          <div className="text-right">
            <span className="block text-xs uppercase tracking-widest font-semibold text-[#888888] mb-1">Progress</span>
            <span className="font-serif text-3xl text-[#1A1A1A]">{progress}%</span>
          </div>
        </div>
      </div>

      {/* Timeline */}
      <div className="relative border-l border-[#EAE7DC] ml-4 md:ml-6 space-y-12 pb-8">
        {roadmapData.modules.map((module, index) => {
          const isCompleted = module.status === 'completed';
          const showVids = activeVideoModule === module._id;

          return (
            <div key={module._id || index} className="relative pl-8 md:pl-12 group">
              
              {/* Timeline Dot */}
              <button 
                onClick={() => handleStatusUpdate(module._id, module.status)}
                className={`absolute -left-[13px] top-1.5 w-6 h-6 rounded-full flex items-center justify-center border-2 transition-colors bg-[#FAF8F5]
                  ${isCompleted ? 'border-[#1A1A1A] bg-[#1A1A1A] text-white' : 'border-[#CCCCCC] text-transparent hover:border-[#1A1A1A]'}`}
              >
                <Check size={14} className={isCompleted ? 'opacity-100' : 'opacity-0'} />
              </button>

              {/* Content Box */}
              <div className={`transition-all duration-300 ${isCompleted ? 'opacity-60' : 'opacity-100'}`}>
                <div className="flex flex-col sm:flex-row sm:items-center gap-3 mb-3">
                  <h3 className="font-serif text-2xl text-[#1A1A1A]">
                    <span className="text-[#888888] mr-2 text-lg">{(index + 1).toString().padStart(2, '0')}.</span>
                    {module.topic}
                  </h3>
                  <span className="inline-flex items-center text-xs font-medium text-[#666666] border border-[#EAE7DC] px-2 py-1 rounded">
                    <Clock size={12} className="mr-1.5" /> {module.estimatedHours} hrs
                  </span>
                </div>
                
                <p className="text-[#4A4A4A] font-light leading-relaxed mb-6">{module.description}</p>
                
                <div className="bg-white border border-[#EAE7DC] rounded-md p-5 mb-6">
                  <h4 className="flex items-center text-xs font-semibold uppercase tracking-widest text-[#1A1A1A] mb-2">
                    <Code2 size={16} className="mr-2 text-[#666666]" /> Milestone Task
                  </h4>
                  <p className="text-[#666666] font-light text-sm">{module.projectIdea}</p>
                </div>

                <div className="flex gap-4">
                  <button 
                    onClick={() => handleFetchVideos(module.topic, module._id)}
                    className="flex items-center text-sm font-medium text-[#1A1A1A] hover:text-[#666666] transition-colors"
                  >
                    <PlaySquare size={16} className="mr-2" /> {showVids ? 'Close Resources' : 'View Resources'}
                  </button>
                  <button 
                    onClick={() => handleStatusUpdate(module._id, module.status)}
                    className="text-sm font-medium text-[#888888] hover:text-[#1A1A1A] transition-colors"
                  >
                    {isCompleted ? 'Mark Incomplete' : 'Mark Complete'}
                  </button>
                </div>

                {/* Video Drawer - Minimalist */}
                {showVids && (
                  <div className="mt-6 bg-white border border-[#EAE7DC] rounded-md p-6">
                    {isVideoLoading ? (
                      <div className="flex items-center text-[#666666] font-light text-sm">
                        <Loader2 className="animate-spin mr-2" size={16} /> Fetching materials...
                      </div>
                    ) : (
                      <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
                        {videos.map((vid) => (
                          <a key={vid.id} href={`https://www.youtube.com/watch?v=${vid.id}`} target="_blank" rel="noreferrer" className="group">
                            <img src={vid.thumbnail} alt={vid.title} className="w-full aspect-video object-cover rounded mb-3 border border-[#EAE7DC] group-hover:border-[#1A1A1A] transition-colors" />
                            <p className="text-sm font-medium text-[#1A1A1A] leading-tight mb-1 line-clamp-2">{vid.title}</p>
                            <p className="text-xs text-[#888888]">{vid.channel}</p>
                          </a>
                        ))}
                      </div>
                    )}
                  </div>
                )}

              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
